-- MySQL Script generated by MySQL Workbench
-- sáb 20 ago 2022 08:58:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tblCorrespondencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblCorrespondencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaentrada` DATETIME NOT NULL,
  `nombreorigen` VARCHAR(255) NOT NULL,
  `totaldocumentosanexos` INT NULL DEFAULT 0,
  `consecutivodocumentosanexos` VARCHAR(200) NULL,
  `fechadocumentoanexo` DATETIME NULL,
  `asuntomensaje` TEXT(1000) NULL,
  `procesodestino` VARCHAR(10) NOT NULL,
  `observaciones` TEXT(65000) NULL,
  `fechaanexoproceso` DATETIME NULL,
  `usuariolector` VARCHAR(30) NOT NULL,
  `usuarioactualizaexpediente` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tblCorrespondencia_tblUsuarios_idx` (`usuariolector` ASC) VISIBLE,
  INDEX `fk_tblCorrespondencia_tblUsuarios1_idx` (`usuarioactualizaexpediente` ASC) VISIBLE,
  CONSTRAINT `fk_tblCorrespondencia_tblUsuarios`
    FOREIGN KEY (`usuariolector`)
    REFERENCES `mydb`.`tblUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblCorrespondencia_tblUsuarios1`
    FOREIGN KEY (`usuarioactualizaexpediente`)
    REFERENCES `mydb`.`tblUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblUsuarios` (
  `id` VARCHAR(30) NOT NULL,
  `apellidosusuario` VARCHAR(50) NOT NULL,
  `nombresusuario` VARCHAR(50) NOT NULL,
  `correousuario` VARCHAR(100) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
